apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-lms
  labels:
    app: nexus-lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexus-lms
  template:
    metadata:
      labels:
        app: nexus-lms
    spec:
      containers:
        - name: nexus-lms
          image: nginxinc/nginx-unprivileged:alpine
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
