apiVersion: v1
kind: Service
metadata:
  name: nexus-lms-service
  labels:
    app: nexus-lms
spec:
  selector:
    app: nexus-lms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
